#ifndef TENSORFLOW_LITE_SUPPORT_CC_TASK_VISION_PROTO_LANDMARKS_PROTO_INC_H_
#define TENSORFLOW_LITE_SUPPORT_CC_TASK_VISION_PROTO_LANDMARKS_PROTO_INC_H_

#include "tensorflow_lite_support/cc/task/vision/proto/class_proto_inc.h"

#include "tensorflow_lite_support/cc/task/vision/proto/landmarks.pb.h"
#endif  // TENSORFLOW_LITE_SUPPORT_CC_TASK_VISION_PROTO_LANDMARKS_PROTO_INC_H_